// resources/js/vue/components/TailwindColorPicker.vue
<script setup lang="ts">
import { ScrollArea } from '@/components/ui/scroll-area';
import { computed, ref } from 'vue';
import IconList from '~icons/heroicons/bars-3';
import IconSearch from '~icons/heroicons/magnifying-glass';
import IconGrid from '~icons/heroicons/squares-2x2';
import { swatchBackground } from '../../lib/color';
import { filterPalette } from '../../lib/tailwind';
import SearchInput from './SearchInput.vue';

const emit = defineEmits<{ select: [value: string] }>();

const search = ref('');
const viewMode = ref<'list' | 'grid'>('list');

const filtered = computed(() => filterPalette(search.value));
</script>

<template>
    <!-- Search + view toggle -->
    <div
        class="border-border bg-card flex items-center gap-2 border-b px-3 py-2"
    >
        <SearchInput
            v-model="search"
            class="flex-1"
            :placeholder="$t('Search Tailwind colors...')"
        />
        <div
            class="border-border flex shrink-0 overflow-hidden rounded-md border"
        >
            <button
                class="cursor-pointer px-2 py-1.5 transition-colors"
                :class="
                    viewMode === 'list'
                        ? 'bg-primary/70 text-primary-foreground'
                        : 'text-muted-foreground hover:bg-primary/10 hover:text-primary'
                "
                :aria-label="$t('List view')"
                @click="viewMode = 'list'"
            >
                <IconList class="size-4" />
            </button>
            <button
                class="cursor-pointer px-2 py-1.5 transition-colors"
                :class="
                    viewMode === 'grid'
                        ? 'bg-primary/70 text-primary-foreground'
                        : 'text-muted-foreground hover:bg-primary/10 hover:text-primary'
                "
                :aria-label="$t('Grid view')"
                @click="viewMode = 'grid'"
            >
                <IconGrid class="size-4" />
            </button>
        </div>
    </div>

    <!-- Color list -->
    <ScrollArea class="h-60">
        <div class="p-2">
            <template v-for="fam in filtered" :key="fam.key">
                <!-- List view -->
                <template v-if="viewMode === 'list'">
                    <button
                        v-for="color in fam.colors"
                        :key="color.name"
                        class="hover:bg-accent focus-visible:ring-ring flex w-full items-center gap-3 rounded-md px-2 py-1.5 text-left transition-colors focus-visible:ring-2 focus-visible:outline-none"
                        @click="emit('select', color.value)"
                    >
                        <span
                            class="border-border/60 size-7 shrink-0 rounded-md border shadow-sm"
                            :style="{
                                background: swatchBackground(color.value),
                            }"
                        />
                        <span class="text-foreground text-sm">
                            {{ color.name }}
                        </span>
                    </button>
                </template>

                <!-- Grid view -->
                <div v-else class="mb-1 grid grid-cols-11 gap-0.5 px-1 py-0.5">
                    <button
                        v-for="color in fam.colors"
                        :key="color.name"
                        class="group focus-visible:outline-none"
                        :title="color.name"
                        @click="emit('select', color.value)"
                    >
                        <span
                            class="border-border/40 group-focus-visible:ring-ring block size-5 rounded border shadow-sm transition-transform group-hover:scale-110 group-focus-visible:ring-2"
                            :style="{
                                background: swatchBackground(color.value),
                            }"
                        />
                    </button>
                </div>
            </template>

            <!-- Empty state -->
            <div
                v-if="filtered.length === 0"
                class="flex flex-col items-center gap-2 py-10 text-center"
            >
                <IconSearch class="text-muted-foreground/40 size-8" />
                <p class="text-muted-foreground text-sm">
                    {{ $t('No colors found') }}
                </p>
            </div>
        </div>
    </ScrollArea>
</template>

// resources/js/react/components/TailwindColorPicker.tsx
import { ScrollArea } from '@/components/ui/scroll-area';
import { useT } from '@/i18n';
import { useState } from 'react';
import IconList from '~icons/heroicons/bars-3';
import IconSearch from '~icons/heroicons/magnifying-glass';
import IconGrid from '~icons/heroicons/squares-2x2';
import { swatchBackground } from '../../lib/color';
import { filterPalette } from '../../lib/tailwind';
import SearchInput from './SearchInput';

export default function TailwindColorPicker({
    onSelect,
}: {
    onSelect: (value: string) => void;
}) {
    const t = useT();
    const [search, setSearch] = useState('');
    const [viewMode, setViewMode] = useState<'list' | 'grid'>('list');

    const filtered = filterPalette(search);

    const viewButtonClass = (mode: 'list' | 'grid') =>
        `cursor-pointer px-2 py-1.5 transition-colors ${
            viewMode === mode
                ? 'bg-primary/70 text-primary-foreground'
                : 'text-muted-foreground hover:bg-primary/10 hover:text-primary'
        }`;

    return (
        <>
            {/* Search + view toggle */}
            <div className="border-border bg-card flex items-center gap-2 border-b px-3 py-2">
                <SearchInput
                    value={search}
                    onChange={setSearch}
                    className="flex-1"
                    placeholder={t('Search Tailwind colors...')}
                />
                <div className="border-border flex shrink-0 overflow-hidden rounded-md border">
                    <button
                        className={viewButtonClass('list')}
                        aria-label={t('List view')}
                        onClick={() => setViewMode('list')}
                    >
                        <IconList className="size-4" />
                    </button>
                    <button
                        className={viewButtonClass('grid')}
                        aria-label={t('Grid view')}
                        onClick={() => setViewMode('grid')}
                    >
                        <IconGrid className="size-4" />
                    </button>
                </div>
            </div>

            {/* Color list */}
            <ScrollArea className="h-60">
                <div className="p-2">
                    {filtered.map((fam) =>
                        viewMode === 'list' ? (
                            fam.colors.map((color) => (
                                <button
                                    key={color.name}
                                    className="hover:bg-accent focus-visible:ring-ring flex w-full items-center gap-3 rounded-md px-2 py-1.5 text-left transition-colors focus-visible:ring-2 focus-visible:outline-none"
                                    onClick={() => onSelect(color.value)}
                                >
                                    <span
                                        className="border-border/60 size-7 shrink-0 rounded-md border shadow-sm"
                                        style={{
                                            background: swatchBackground(
                                                color.value,
                                            ),
                                        }}
                                    />
                                    <span className="text-foreground text-sm">
                                        {color.name}
                                    </span>
                                </button>
                            ))
                        ) : (
                            <div
                                key={fam.key}
                                className="mb-1 grid grid-cols-11 gap-0.5 px-1 py-0.5"
                            >
                                {fam.colors.map((color) => (
                                    <button
                                        key={color.name}
                                        className="group focus-visible:outline-none"
                                        title={color.name}
                                        onClick={() => onSelect(color.value)}
                                    >
                                        <span
                                            className="border-border/40 group-focus-visible:ring-ring block size-5 rounded border shadow-sm transition-transform group-hover:scale-110 group-focus-visible:ring-2"
                                            style={{
                                                background: swatchBackground(
                                                    color.value,
                                                ),
                                            }}
                                        />
                                    </button>
                                ))}
                            </div>
                        ),
                    )}

                    {/* Empty state */}
                    {filtered.length === 0 && (
                        <div className="flex flex-col items-center gap-2 py-10 text-center">
                            <IconSearch className="text-muted-foreground/40 size-8" />
                            <p className="text-muted-foreground text-sm">
                                {t('No colors found')}
                            </p>
                        </div>
                    )}
                </div>
            </ScrollArea>
        </>
    );
}
