// resources/js/react/components/SearchInput.tsx
import IconSearch from '~icons/heroicons/magnifying-glass';
import IconX from '~icons/lucide/x';

interface SearchInputProps {
    value: string;
    onChange: (value: string) => void;
    placeholder?: string;
    testId?: string;
    className?: string;
}

export default function SearchInput({
    value,
    onChange,
    placeholder,
    testId,
    className = '',
}: SearchInputProps) {
    return (
        <div
            className={`border-border focus-within:border-ring focus-within:ring-primary flex items-center gap-2 rounded-full border px-3 focus-within:ring-2 ${className}`}
        >
            <input
                value={value}
                onChange={(e) => onChange(e.target.value)}
                type="text"
                placeholder={placeholder}
                data-testid={testId}
                className="text-foreground placeholder:text-muted-foreground flex-1 border-none bg-transparent text-sm ring-0 outline-none"
            />
            {value ? (
                <IconX
                    className="text-muted-foreground size-4 shrink-0 cursor-pointer"
                    onClick={() => onChange('')}
                />
            ) : (
                <IconSearch
                    className="text-muted-foreground size-4 shrink-0"
                    aria-hidden="true"
                />
            )}
        </div>
    );
}

// resources/js/components/SearchInput.vue
<script setup lang="ts">
import IconSearch from '~icons/heroicons/magnifying-glass';

defineProps<{ placeholder?: string; testId?: string }>();
const model = defineModel<string>({ default: '' });
</script>

<template>
    <div class="flex items-center gap-2 rounded-full border border-border px-3  focus-within:border-ring focus-within:ring-2 focus-within:ring-primary">
        <input
            v-model="model"
            type="text"
            :placeholder="placeholder"
            :data-testid="testId"
            class="flex-1 bg-transparent text-sm text-foreground placeholder:text-muted-foreground border-none outline-none ring-0"
        />
        <IconSearch class="size-4 shrink-0 text-muted-foreground" aria-hidden="true" />
    </div>
</template>
