// resources/js/react/components/DialogSave.tsx
import { Button } from '@/components/ui/button';
import {
    Dialog,
    DialogContent,
    DialogDescription,
    DialogHeader,
    DialogTitle,
} from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { useT } from '@/i18n';
import { router, useHttp } from '@inertiajs/react';
import { httpFailureHandlers } from '@js/lib/http';
import { useState } from 'react';
import { toast } from 'sonner';
import IconSave from '~icons/lucide/save';
import type { ThemePayload } from '../../lib/panel';
import type { Theme } from '../../types';

interface DialogSaveProps {
    open: boolean;
    onOpenChange: (open: boolean) => void;
    toJson: (name: string) => ThemePayload;
    /** Gets the reloaded theme list, which already includes the new theme. */
    onThemeSaved?: (id: string, themes: Theme[]) => void;
}

export default function DialogSave({
    open,
    onOpenChange,
    toJson,
    onThemeSaved,
}: DialogSaveProps) {
    const t = useT();
    const http = useHttp({});
    const [name, setName] = useState('');
    const [loading, setLoading] = useState(false);

    function close() {
        onOpenChange(false);
        setName('');
    }

    function handleSave() {
        if (!name.trim() || loading) return;
        const payload = toJson(name);

        setLoading(true);
        http.transform(() => payload);
        http.post(route('themes.store'), {
            onSuccess() {
                router.reload({
                    only: ['themes'],
                    onSuccess: (reloaded) => {
                        onThemeSaved?.(
                            payload.name,
                            (reloaded.props.themes?.items as Theme[]) ?? [],
                        );
                        close();
                        toast.success(t('Theme saved successfully'), {
                            testId: 'theme-saved-toast',
                        });
                        setLoading(false);
                    },
                });
            },
            onError(errors: Record<string, string>) {
                toast.error(t(errors?.name ?? 'Failed to save theme'));
                setLoading(false);
            },
            // `onError` covers 422s only; these say the rest.
            ...httpFailureHandlers((message) => {
                toast.error(t(message));
                setLoading(false);
            }),
        }).catch(() => {});
    }

    return (
        // Same layout as the app's confirm dialog (DynamicDialog), plus the name input.
        <Dialog open={open} onOpenChange={onOpenChange}>
            <DialogContent
                className="overflow-hidden p-0 sm:max-w-sm"
                showCloseButton={false}
                onEscapeKeyDown={(e) => e.preventDefault()}
                onPointerDownOutside={(e) => e.preventDefault()}
            >
                <div className="bg-background flex flex-col items-center p-6 text-center">
                    <div className="bg-primary/10 text-primary mb-4 flex size-14 items-center justify-center rounded-xl">
                        <IconSave className="size-7" />
                    </div>
                    <DialogHeader className="sm:text-center">
                        <DialogTitle>{t('Save theme')}</DialogTitle>
                        <DialogDescription>
                            {t(
                                'Save this theme to reuse it later without reconfiguring colors, fonts, and radius.',
                            )}
                        </DialogDescription>
                    </DialogHeader>
                    <Input
                        value={name}
                        className="mt-4"
                        data-testid="save-theme-name"
                        placeholder={t('Theme name')}
                        disabled={loading}
                        onChange={(e) => setName(e.target.value)}
                        onKeyDown={(e) => e.key === 'Enter' && handleSave()}
                    />
                </div>
                <div className="bg-muted/50 border-t p-4">
                    <div className="grid grid-cols-2 gap-4">
                        <Button
                            variant="outline"
                            className="dark:hover:bg-accent dark:hover:text-accent-foreground w-full"
                            data-testid="save-theme-cancel"
                            disabled={loading}
                            onClick={close}
                        >
                            {t('Cancel')}
                        </Button>
                        <Button
                            className="w-full"
                            data-testid="save-theme-submit"
                            disabled={!name.trim() || loading}
                            onClick={handleSave}
                        >
                            {loading ? t('Saving...') : t('Save')}
                        </Button>
                    </div>
                </div>
            </DialogContent>
        </Dialog>
    );
}

// resources/js/vue/components/DialogSave.vue
<script setup lang="ts">
import { Button } from '@/components/ui/button';
import {
    Dialog,
    DialogContent,
    DialogDescription,
    DialogHeader,
    DialogTitle,
} from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { router, useHttp } from '@inertiajs/vue3';
import { httpFailureHandlers } from '@js/lib/http';
import { trans } from 'laravel-vue-i18n';
import { computed, ref } from 'vue';
import { toast } from 'vue-sonner';
import IconSave from '~icons/lucide/save';

const open = defineModel<boolean>({ default: false });

const props = defineProps<{
    toJson: (name: string) => {
        name: string;
        title: string;
        description: string;
        cssVars: {
            theme?: Record<string, string>;
            light: Record<string, string>;
            dark: Record<string, string>;
        };
    };
    onThemeSaved?: (id: string) => void;
}>();

const name = ref('');
const loading = ref(false);
const isLoading = computed(() => loading.value);

const handleCancel = () => {
    open.value = false;
    name.value = '';
};

const handleSave = async () => {
    const payload = props.toJson(name.value);
    const http = useHttp(payload).withAllErrors();

    http.post(route('themes.store'), {
        onBefore() {
            loading.value = true;
        },
        onSuccess() {
            router.reload({
                only: ['themes'],
                onSuccess: () => {
                    props.onThemeSaved?.(payload.name);
                    open.value = false;
                    name.value = '';
                    toast.success(trans('Theme saved successfully'), {
                        testId: 'theme-saved-toast',
                    });
                    loading.value = false;
                },
            });
        },
        onError: (errors) => {
            if (errors?.name) toast.error(trans(errors.name));
            else toast.error(trans('Failed to save theme'));
            return true;
        },
        // `onError` covers 422s only; these say the rest.
        ...httpFailureHandlers((message) => toast.error(trans(message))),
        onFinish: () => {
            loading.value = false;
        },
    }).catch(() => {});
};
</script>

<template>
    <!-- Same layout as the app's confirm dialog (DynamicDialog), plus the name input. -->
    <Dialog :open="open" @update:open="(v) => (open = v)">
        <DialogContent
            class="overflow-hidden p-0 sm:max-w-sm"
            :show-close-button="false"
            @escape-key-down="(e) => e.preventDefault()"
            @pointer-down-outside="(e) => e.preventDefault()"
        >
            <div
                class="bg-background flex flex-col items-center p-6 text-center"
            >
                <div
                    class="bg-primary/10 text-primary mb-4 flex size-14 items-center justify-center rounded-xl"
                >
                    <IconSave class="size-7" />
                </div>
                <DialogHeader class="sm:text-center">
                    <DialogTitle>{{ $t('Save theme') }}</DialogTitle>
                    <DialogDescription>
                        {{
                            $t(
                                'Save this theme to reuse it later without reconfiguring colors, fonts, and radius.',
                            )
                        }}
                    </DialogDescription>
                </DialogHeader>
                <Input
                    v-model="name"
                    class="mt-4"
                    data-testid="save-theme-name"
                    :placeholder="$t('Theme name')"
                    :disabled="isLoading"
                    @keydown.enter="handleSave"
                />
            </div>
            <div class="bg-muted/50 border-t p-4">
                <div class="grid grid-cols-2 gap-4">
                    <Button
                        variant="outline"
                        class="dark:hover:bg-accent dark:hover:text-accent-foreground w-full"
                        data-testid="save-theme-cancel"
                        :disabled="isLoading"
                        @click="handleCancel"
                    >
                        {{ $t('Cancel') }}
                    </Button>
                    <Button
                        class="w-full"
                        data-testid="save-theme-submit"
                        :disabled="!name.trim() || isLoading"
                        @click="handleSave"
                    >
                        {{ isLoading ? $t('Saving...') : $t('Save') }}
                    </Button>
                </div>
            </div>
        </DialogContent>
    </Dialog>
</template>
